/**
 * Generated by veryExpress@0.5.15 
 * https://github.com/Justin26l/VeryExpress
 */

export class _ControllerFactory {

    constructor() {}

    protected isObjectId(id: string): boolean {
        return /^[0-9a-fA-F]{24}$/.test(id);
    }
    
}