/**
 * Generated by veryExpress@0.5.11 
 * https://github.com/Justin26l/VeryExpress
 */

import * as controllerFactory from "./_ControllerFactory.gen";
import { Router, Request, Response } from 'express';

import { checkSchema, validationResult } from 'express-validator';
import vex from "./../../system/_utils/index.gen";
import MongoQS from 'mongo-ts-querystring';

import { SessionModel } from '../_models/SessionModel.gen';

class SessionController extends controllerFactory._ControllerFactory {
    public router: Router;

    constructor() {
        super();
        this.router = Router();
        this.routes();
    }

    public routes() {
        
        
        // getListRoute disabled

        
        // getRoute disabled

        
        // postRoute disabled

        
        // putRoute disabled

        
        // patchRoute disabled

        
        // deleteRoute disabled

    };

    public async getSession(req: Request, res: Response): Promise<Response> {
        try {
            const validationError = validationResult(req);
            if ( ! validationError.isEmpty() ) {
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_validation, 
                    result: validationError.array()
                });
            };

            const result = await SessionModel.findById(req.params.id);

            if (!result) {
                return vex.response.send(res, 404);
            }
            else {
                return vex.response.send(res, 200, { result });
            };
        } catch (err:any) {
            return vex.response.send(res, 500, { message: err.message });
        }
    }

    public async getListSession(req: Request, res: Response): Promise<Response> {
        try {
            const validationError = validationResult(req);
            if ( ! validationError.isEmpty() ) {
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_validation, 
                    result: validationError.array()
                });
            };
            
            const searchFilter = new MongoQS().parse(req.query);
            delete searchFilter._select;
            delete searchFilter._join;
            
            let selectedFields : {[key: string]: number} | undefined = undefined;
            let populateOptions : any | undefined = undefined;

            try { 
                selectedFields = vex.common.parseFieldsSelect(req);
                populateOptions = vex.common.parseCollectionJoin(req, {});
            } 
            catch (err:any) { 
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_validation, 
                    result: err.message
                });
            };

            const result = await SessionModel.find(searchFilter, selectedFields).populate(populateOptions);
            return vex.response.send(res, 200, { result });
        } catch (err:any) {
            return vex.response.send(res, 500, { result: err.message });
        }
    }

    public async createSession(req: Request, res: Response): Promise<Response> {
        try {
            const validationError = validationResult(req);
            if ( ! validationError.isEmpty() ) {
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_validation, 
                    result: validationError.array()
                });
            };
            if (req.body._id) {
                delete req.body._id;
            };
            
            const result = await SessionModel.create(req.body);
            if (!result) {
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_create
                });
            }
            else {
                return vex.response.send(res, 201, {result});
            };
        } catch (err:any) {
            return vex.response.send(res, 500, { message: err.message });
        };
    };

    public async updateSession(req: Request, res: Response): Promise<Response> {
        try {
            const validationError = validationResult(req);
            if ( ! validationError.isEmpty() ) {
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_validation, 
                    result: validationError.array()
                });
            };
            if (req.body._id) {
                delete req.body._id;
            };

            const result = await SessionModel.findByIdAndUpdate(req.params.id, req.body, { new: true });
            if (!result) {
                return vex.response.send(res, 404, {
                    code: vex.response.code.err_update
                });
            }
            else {
                return vex.response.send(res, 200, { result });
            };
        } catch (err:any) {
            return vex.response.send(res, 500, { message: err.message });
        }
    }

    public async replaceSession(req: Request, res: Response): Promise<Response> {
        try {
            const validationError = validationResult(req);
            if ( ! validationError.isEmpty() ) {
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_validation, 
                    result: validationError.array()
                });
            };
            if (req.body._id) {
                delete req.body._id;
            };

            const result = await SessionModel.replaceOne({_id: req.params.id}, req.body);
            if (!result) {
                return vex.response.send(res, 404, { 
                    code: vex.response.code.err_update
                });
            }
            else {
                return vex.response.send(res, 200, { result });
            };
        } catch (err:any) {
            return vex.response.send(res, 500, { message: err.message });
        }
    }

    public async deleteSession(req: Request, res: Response): Promise<Response> {
        try {
            const validationError = validationResult(req);
            if ( ! validationError.isEmpty() ) {
                return vex.response.send(res, 400, {
                    code: vex.response.code.err_validation, 
                    result: validationError.array()
                });
            };

            const result = await SessionModel.findByIdAndDelete(req.params.id);
            if (!result) {
                return vex.response.send(res, 404, {
                    code: vex.response.code.err_delete
                });
            }
            else {
                return vex.response.send(res, 204, { result });
            };
        } catch (err:any) {
            return vex.response.send(res, 500, { message: err.message });
        }
    }
}

export default new SessionController().router;
