/**
 * Generated by veryExpress@0.5.11 
 * https://github.com/Justin26l/VeryExpress
 */

import * as roleFactory from "./../../system/_roles/_RoleFactory.gen";

export type accessActionuser = roleFactory.accessAction;

const userAccessControl: roleFactory.accessControl<accessActionuser> = {
    "Session": [
        "create",
        "read",
        "update",
        "delete"
    ],
    "User": [
        "create",
        "read",
        "update",
        "delete"
    ]
};

export default class Roleuser extends roleFactory._RoleFactory<accessActionuser> {
    constructor() {
        super(userAccessControl);
    }
}
