/**
 * Generated by veryExpress@0.5.15 
 * https://github.com/Justin26l/VeryExpress
 */

import { Router } from 'express';

import RoleBaseAccessControl from '../_middlewares/RoleBaseAccessControl.gen';
import CustomerController from '../_controllers/CustomerController.gen';
import SessionController from '../_controllers/SessionController.gen';
import UserController from '../_controllers/UserController.gen';

export default class ApiRouter{

    private router: Router = Router();

    constructor() {
        this.router.use('/Customer', new RoleBaseAccessControl('Customer').middleware,  CustomerController);
        this.router.use('/Session', new RoleBaseAccessControl('Session').middleware,  SessionController);
        this.router.use('/User', new RoleBaseAccessControl('User').middleware,  UserController);
    }

    public getRouter() {
        return this.router;
    }

}